name: Kaktus Dobíječka Notifikátor

on:
  schedule:
    # Běží v 7. a 37. minutě mezi 6:00 a 19:59 UTC
    # V létě: 8:00 - 21:59 ČR | V zimě: 7:00 - 20:59 ČR
    - cron: '7,37 6-19 * * *'
  workflow_dispatch:


permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Stažení repozitáře
        uses: actions/checkout@v4

      - name: Nastavení Pythonu
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalace knihoven
        run: |
          pip install -r requirements.txt

      - name: Spuštění skriptu
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python kaktus_bot.py

      - name: Uložení paměti zpět do repozitáře
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add posledni_zprava.txt || true
          git commit -m "Aktualizace posledního termínu [skip ci]" || true
          git push || true
