name: Kaktus Dobíječka Notifikátor

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Stažení repozitáře
        uses: actions/checkout@v4

      - name: Nastavení Pythonu
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalace knihoven
        run: |
          pip install -r requirements.txt

      - name: Spuštění skriptu
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python kaktus_bot.py

      - name: Uložení paměti zpět do repozitáře
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add posledni_zprava.txt
          git diff-index --quiet HEAD || git commit -m "Aktualizace posledního termínu"
          git push
